### ISSUE TITLE
IndexError: index 622 is out of bounds for axis 0 with size 621

### ISSUE THREAD

**Issue by B10956048** [shizenglin/training-free-object-counter#1]
Hello, 

I encountered an error when running the command `python main-fsc147.py --test-split='test' --prompt-type='box' --device='cuda:0'`. The error traceback is as follows:

```
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\count\training-free-object-counter\main-fsc147.py", line 108, in <module>
    masks = mask_generator.generate(image, input_prompt)
  File "C:\Users\User\PycharmProjects\count\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\User\PycharmProjects\count\training-free-object-counter\shi_segment_anything\automatic_mask_generator.py", line 170, in generate
  File "C:\Users\User\PycharmProjects\count\training-free-object-counter\shi_segment_anything\automatic_mask_generator.py", line 374, in _process_batch
    transformed_labels = sim_map[[transformed_points[:, 1], transformed_points[:, 0]]]
IndexError: index 622 is out of bounds for axis 0 with size 621
```

I would like to ask if there is a solution to this problem or if there is something I might have overlooked.
Thank you.

**Comment by shizenglin** [comment]
Please check your input size is in the format of  "width, height" or "height, width"

**Comment by B10956048** [comment]
Are you referring to the size of the image? When my image has the shape of the original image, for instance (384, 633, 3), I encounter this error. However, when I resize the image to (512, 512, 3), the issue disappears(but it then leads to a mismatch in dimensions down the line). Thus, I am wondering if there is a specific image size format that I should adhere to?

**Comment by HeyLinyuhao** [comment]
Hi, I have the same issue. Have you solved?

**Comment by HeyLinyuhao** [comment]
Solved, replace the line with 'transformed_labels = sim_map[(transformed_points[:,1],transformed_points[:,0])]'
